
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bernardo
 */
public class AdministradorGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdministradorGUI
     */
    public AdministradorGUI() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_SO = new javax.swing.JButton();
        Button_CD = new javax.swing.JButton();
        Button_IdO = new javax.swing.JButton();
        Button_FdP = new javax.swing.JButton();
        Button_CE = new javax.swing.JButton();
        Button_TdE = new javax.swing.JButton();
        Button_EdD = new javax.swing.JButton();
        Button_MD = new javax.swing.JButton();
        Button_CV = new javax.swing.JButton();
        Button_TdA = new javax.swing.JButton();
        Button_AL = new javax.swing.JButton();
        Button_Q = new javax.swing.JButton();
        Button_CF = new javax.swing.JButton();
        Button_POaO = new javax.swing.JButton();
        Button_CI = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Button_SO.setText("SISTEMAS OPERATIVOS");
        Button_SO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SOActionPerformed(evt);
            }
        });

        Button_CD.setText("CALCULO DIFERENCIAL");
        Button_CD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CDActionPerformed(evt);
            }
        });

        Button_IdO.setText("INVESTIGACION DE OPERACIONES");
        Button_IdO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_IdOActionPerformed(evt);
            }
        });

        Button_FdP.setText("FUNDAMENTOS DE PROGRAMACION");
        Button_FdP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_FdPActionPerformed(evt);
            }
        });

        Button_CE.setText("CULTURA EMPRESARIAL");
        Button_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CEActionPerformed(evt);
            }
        });

        Button_TdE.setText("TALLER DE ETICA");
        Button_TdE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TdEActionPerformed(evt);
            }
        });

        Button_EdD.setText("ESTRUCTURA DE DATOS");
        Button_EdD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EdDActionPerformed(evt);
            }
        });

        Button_MD.setText("MATEMATICAS DISCRETAS");
        Button_MD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_MDActionPerformed(evt);
            }
        });

        Button_CV.setText("CALCULO VECTORIAL");
        Button_CV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CVActionPerformed(evt);
            }
        });

        Button_TdA.setText("TALLER DE ADMINISTRACION");
        Button_TdA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TdAActionPerformed(evt);
            }
        });

        Button_AL.setText("ALGEBRA LINEAL");
        Button_AL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ALActionPerformed(evt);
            }
        });

        Button_Q.setText("QUIMICA");
        Button_Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_QActionPerformed(evt);
            }
        });

        Button_CF.setText("CONTABILIDAD FINANCIERA");
        Button_CF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CFActionPerformed(evt);
            }
        });

        Button_POaO.setText("PROGRAMACION ORIENTADA A OBJETOS");
        Button_POaO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_POaOActionPerformed(evt);
            }
        });

        Button_CI.setText("CALCULO INTEGRAL");
        Button_CI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CIActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel3.setText("Informacion sobre las materias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_CD, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_FdP, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_TdE, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_MD, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_TdA, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_CI, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_POaO, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_CF, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_AL, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_CV, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_EdD, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_IdO, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_SO, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_CD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_CI, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_CV, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_FdP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_POaO, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_EdD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_TdE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_CF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_MD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_IdO, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_TdA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_AL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_SO, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void lista_CD(){
        IngresoGUI n=new IngresoGUI();
        Lista_CD r=n.p1;
        String res="No Control          Nombre\n";
        do{
                    res+=r.noControl+"          "+r.nombre+""+"\n";
                    r=r.liga;
        }while(r!=null);
               JOptionPane.showMessageDialog(null, res);
    }
    
    public void lista_FdP(){
       IngresoGUI n=new IngresoGUI();
        Lista_FdP r=n.p2;
        String res="No Control          Nombre\n";
        do{
                    res+=r.noControl+"          "+r.nombre+""+"\n";
                    r=r.liga;
        }while(r!=null);
               JOptionPane.showMessageDialog(null, res); 
    }
    
    public void lista_TdE(){
       IngresoGUI n=new IngresoGUI();
        Lista_TdE r=n.p3;
        String res="No Control          Nombre\n";
        do{
                    res+=r.noControl+"          "+r.nombre+""+"\n";
                    r=r.liga;
        }while(r!=null);
               JOptionPane.showMessageDialog(null, res); 
    }
    
    public void lista_MD(){
        IngresoGUI n=new IngresoGUI();
        Lista_MD r=n.p4;
        String res="No Control          Nombre\n";
        do{
                    res+=r.noControl+"          "+r.nombre+""+"\n";
                    r=r.liga;
        }while(r!=null);
               JOptionPane.showMessageDialog(null, res);  
    }
    
    public void lista_TdA(){
       IngresoGUI n=new IngresoGUI();
        Lista_TdA r=n.p5;
        String res="No Control          Nombre\n";
        do{
                    res+=r.noControl+"          "+r.nombre+""+"\n";
                    r=r.liga;
        }while(r!=null);
               JOptionPane.showMessageDialog(null, res);  
    }
    
    public void lista_CI(){
        IngresoGUI n=new IngresoGUI();
        Lista_CI r=n.p6;
        String res="No Control          Nombre\n";
        do{
                    res+=r.noControl+"          "+r.nombre+""+"\n";
                    r=r.liga;
        }while(r!=null);
               JOptionPane.showMessageDialog(null, res);   
    }
    
    public void lista_POaO(){
        IngresoGUI n=new IngresoGUI();
        Lista_POaO r=n.p7;
        String res="No Control          Nombre\n";
        do{
                    res+=r.noControl+"          "+r.nombre+""+"\n";
                    r=r.liga;
        }while(r!=null);
               JOptionPane.showMessageDialog(null, res);
    }
    
    public void lista_CF(){
         IngresoGUI n=new IngresoGUI();
        Lista_CF r=n.p8;
        String res="No Control          Nombre\n";
        do{
                    res+=r.noControl+"          "+r.nombre+""+"\n";
                    r=r.liga;
        }while(r!=null);
               JOptionPane.showMessageDialog(null, res);
    }
    
    public void lista_Q(){
       IngresoGUI n=new IngresoGUI();
        Lista_Q r=n.p9;
        String res="No Control          Nombre\n";
        do{
                    res+=r.noControl+"          "+r.nombre+""+"\n";
                    r=r.liga;
        }while(r!=null);
               JOptionPane.showMessageDialog(null, res); 
    }
    
    public void lista_AL(){
       IngresoGUI n=new IngresoGUI();
        Lista_AL r=n.p10;
        String res="No Control          Nombre\n";
        do{
                    res+=r.noControl+"          "+r.nombre+""+"\n";
                    r=r.liga;
        }while(r!=null);
               JOptionPane.showMessageDialog(null, res);  
    }
    
    public void lista_CV(){
       IngresoGUI n=new IngresoGUI();
        Lista_CV r=n.p11;
        String res="No Control          Nombre\n";
        do{
                    res+=r.noControl+"          "+r.nombre+""+"\n";
                    r=r.liga;
        }while(r!=null);
        JOptionPane.showMessageDialog(null, res);  
    }
    
    public void lista_EdD(){
        IngresoGUI n=new IngresoGUI();
        Lista_EdD r=n.p12;
        String res="No Control          Nombre\n";
        do{
                    res+=r.noControl+"          "+r.nombre+""+"\n";
                    r=r.liga;
        }while(r!=null);
        JOptionPane.showMessageDialog(null, res);   
    }
    
    public void lista_CE(){
        IngresoGUI n=new IngresoGUI();
        Lista_CE r=n.p13;
        String res="No Control          Nombre\n";
        do{
                    res+=r.noControl+"          "+r.nombre+""+"\n";
                    r=r.liga;
        }while(r!=null);
        JOptionPane.showMessageDialog(null, res); 
    }
    
    public void lista_IdO(){
       IngresoGUI n=new IngresoGUI();
        Lista_IdO r=n.p14;
        String res="No Control          Nombre\n";
        do{
                    res+=r.noControl+"          "+r.nombre+""+"\n";
                    r=r.liga;
        }while(r!=null);
        JOptionPane.showMessageDialog(null, res);  
    }
    
    public void lista_SO(){
        IngresoGUI n=new IngresoGUI();
        Lista_SO r=n.p15;
        String res="No Control          Nombre\n";
        do{
                    res+=r.noControl+"          "+r.nombre+""+"\n";
                    r=r.liga;
        }while(r!=null);
        JOptionPane.showMessageDialog(null, res);  
    }
    
    private void Button_SOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SOActionPerformed
        AdministradorGUI ref=new AdministradorGUI();
       ref.lista_SO();
    }//GEN-LAST:event_Button_SOActionPerformed

    private void Button_IdOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_IdOActionPerformed
        AdministradorGUI ref=new AdministradorGUI();
       ref.lista_IdO();
    }//GEN-LAST:event_Button_IdOActionPerformed

    private void Button_FdPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_FdPActionPerformed
       AdministradorGUI ref=new AdministradorGUI();
       ref.lista_FdP();
    }//GEN-LAST:event_Button_FdPActionPerformed

    private void Button_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CEActionPerformed
         AdministradorGUI ref=new AdministradorGUI();
       ref.lista_CE();
    }//GEN-LAST:event_Button_CEActionPerformed

    private void Button_TdEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TdEActionPerformed
       AdministradorGUI ref=new AdministradorGUI();
       ref.lista_TdE();
    }//GEN-LAST:event_Button_TdEActionPerformed

    private void Button_EdDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EdDActionPerformed
        AdministradorGUI ref=new AdministradorGUI();
       ref.lista_EdD();
    }//GEN-LAST:event_Button_EdDActionPerformed

    private void Button_MDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_MDActionPerformed
        AdministradorGUI ref=new AdministradorGUI();
       ref.lista_MD();
    }//GEN-LAST:event_Button_MDActionPerformed

    private void Button_TdAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TdAActionPerformed
         AdministradorGUI ref=new AdministradorGUI();
       ref.lista_TdA();
    }//GEN-LAST:event_Button_TdAActionPerformed

    private void Button_ALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ALActionPerformed
        AdministradorGUI ref=new AdministradorGUI();
       ref.lista_AL();
    }//GEN-LAST:event_Button_ALActionPerformed

    private void Button_QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_QActionPerformed
        AdministradorGUI ref=new AdministradorGUI();
       ref.lista_Q();
    }//GEN-LAST:event_Button_QActionPerformed

    private void Button_CFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CFActionPerformed
       AdministradorGUI ref=new AdministradorGUI();
       ref.lista_CF();
    }//GEN-LAST:event_Button_CFActionPerformed

    private void Button_POaOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_POaOActionPerformed
       AdministradorGUI ref=new AdministradorGUI();
       ref.lista_POaO();
    }//GEN-LAST:event_Button_POaOActionPerformed
       
    private void Button_CDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CDActionPerformed
       AdministradorGUI ref=new AdministradorGUI();
       ref.lista_CD();
    }//GEN-LAST:event_Button_CDActionPerformed

    private void Button_CIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CIActionPerformed
       AdministradorGUI ref=new AdministradorGUI();
       ref.lista_CI();
    }//GEN-LAST:event_Button_CIActionPerformed

    private void Button_CVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CVActionPerformed
       AdministradorGUI ref=new AdministradorGUI();
       ref.lista_CV();
    }//GEN-LAST:event_Button_CVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_AL;
    private javax.swing.JButton Button_CD;
    private javax.swing.JButton Button_CE;
    private javax.swing.JButton Button_CF;
    private javax.swing.JButton Button_CI;
    private javax.swing.JButton Button_CV;
    private javax.swing.JButton Button_EdD;
    private javax.swing.JButton Button_FdP;
    private javax.swing.JButton Button_IdO;
    private javax.swing.JButton Button_MD;
    private javax.swing.JButton Button_POaO;
    private javax.swing.JButton Button_Q;
    private javax.swing.JButton Button_SO;
    private javax.swing.JButton Button_TdA;
    private javax.swing.JButton Button_TdE;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
