
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrador
 */
public class IngresoGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    //IMPLEMENTACIÓN CON ARRAYS
    String noControl[]={"16041201","16041202","16041203","16041204","16041205","16041206","16041207","16041208","16041209","16041210"};
    String nip[]={"1111","2222","3333","4444","5555","6666","7777","8888","9999","0000"};
    String nombre[]={"CARRILLO MARTINEZ ALEJANDRO DE JESUS","DERAS BONILLA CRISTOPHER JARED","MEDRANO CORRAL ALEJANDRO",
        "SALINAS JAQUEZ BERNARDO","ALARCON GARVALENA LAURA YESENIA","ALVAREZ DELGADO ROQUE EMILIO","AMAYA COLACION HELADIO",
        "CASTAÑEDA ALVARADO CHRISTOPHER","CELIS CARRILLO SAMANTHA DEL CARMEN","CHAVARRIA CABRALES AGUSTIN"};
    int semestre[]={3,2,3,3,2,1,2,3,3,2};
    
    

    
    
    
    public IngresoGUI() {
        initComponents();
        this.setResizable(false);
        //Codigo para poner imagen de fondo
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/AtM.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        
        //IMPLEMENTACIÓN CON LISTAS
        Random r = new Random();
        Lista ALUMNOS = new Lista();
                                            //Nombre,                    NoControl, Semestre, Random Double(50-100)
        ALUMNOS.insertarUltimo("Alejandro de Jesús Carrillo Mártinez", "16041213", 3, 50 + (100 - 50) * r.nextDouble());
        ALUMNOS.insertarUltimo("Alejandro Medrano Corral", "16042345", 3, 50 + (100 - 50) * r.nextDouble());
        ALUMNOS.insertarUltimo("Alejandro de Jesús Carrillo Mártinez", "16041213", 3, 50 + (100 - 50) * r.nextDouble());
        ALUMNOS.insertarUltimo("Alejandro de Jesús Carrillo Mártinez", "16041213", 3, 50 + (100 - 50) * r.nextDouble());
        ALUMNOS.insertarUltimo("Alejandro de Jesús Carrillo Mártinez", "16041213", 3, 50 + (100 - 50) * r.nextDouble());
        ALUMNOS.insertarUltimo("Alejandro de Jesús Carrillo Mártinez", "16041213", 3, 50 + (100 - 50) * r.nextDouble());
        ALUMNOS.insertarUltimo("Alejandro de Jesús Carrillo Mártinez", "16041213", 3, 50 + (100 - 50) * r.nextDouble());
        ALUMNOS.insertarUltimo("Alejandro de Jesús Carrillo Mártinez", "16041213", 3, 50 + (100 - 50) * r.nextDouble());
        ALUMNOS.insertarUltimo("Alejandro de Jesús Carrillo Mártinez", "16041213", 3, 50 + (100 - 50) * r.nextDouble());
        ALUMNOS.insertarUltimo("Alejandro de Jesús Carrillo Mártinez", "16041213", 3, 50 + (100 - 50) * r.nextDouble());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFieldNoControl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonIngresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ButtonSoyAdmin = new javax.swing.JButton();
        PasswordFieldContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Número de Control");

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("NIP");

        ButtonIngresar.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        ButtonIngresar.setForeground(new java.awt.Color(0, 102, 255));
        ButtonIngresar.setText("INGRESAR");
        ButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIngresarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Gloss And Bloom", 1, 34)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Sistema InTegral de Información 2.0");

        ButtonSoyAdmin.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        ButtonSoyAdmin.setForeground(new java.awt.Color(0, 102, 255));
        ButtonSoyAdmin.setText("¡SOY ADMINISTRADOR!");
        ButtonSoyAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSoyAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(286, 286, 286)
                                .addComponent(ButtonIngresar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButtonSoyAdmin)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(33, 33, 33))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(83, 83, 83)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PasswordFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextFieldNoControl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(TextFieldNoControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(ButtonIngresar)
                .addGap(18, 18, 18)
                .addComponent(ButtonSoyAdmin)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIngresarActionPerformed
        String no=TextFieldNoControl.getText();
        String nip2=PasswordFieldContraseña.getText();
        if(no.equals("") || nip2.equals("")){
            JOptionPane.showMessageDialog(null,"Asegurate de llenar todos los datos de usuario");
        }else{
            int pos=0;
            int bandera=0;
            for(int i=0;i<10;i++){
                if(noControl[i].equals(no)){
                    pos=i;
                    bandera=1;
                    break;
                }
            }
            if(bandera==1){
                if(nip[pos].equals(nip2)){
                   MateriasGUI n=new MateriasGUI();
                   MateriasGUI.jLabel2.setText(nombre[pos]);
                   n.setVisible(true);
                   this.setVisible(false);
                }else{
                JOptionPane.showMessageDialog(null,"El nip ingresado no es correcto");
                TextFieldNoControl.setText("");
                PasswordFieldContraseña.setText(""); 
                }
            }else{
                JOptionPane.showMessageDialog(null,"El numero de control no esta registrado");
                TextFieldNoControl.setText("");
                PasswordFieldContraseña.setText("");
            }
        }
    }//GEN-LAST:event_ButtonIngresarActionPerformed

    private void ButtonSoyAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSoyAdminActionPerformed
        //Estos los datos para ingresar como administrador (Profesor)
        String usuario=JOptionPane.showInputDialog(null,"Ingresa el usuario");
        //Usuario: admin
        if(usuario.equals("admin")){
            String pass=JOptionPane.showInputDialog("Ingresa el nip");
            //Password: 2371
            if(pass.equals("2371")){
                AdministradorGUI n=new AdministradorGUI();
                n.setVisible(true);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null,"EL nip ingresado no es correcto");
            }
        }else{
            JOptionPane.showMessageDialog(null,"EL usuario no es correcto");
        }
    
    }//GEN-LAST:event_ButtonSoyAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonIngresar;
    private javax.swing.JButton ButtonSoyAdmin;
    private javax.swing.JPasswordField PasswordFieldContraseña;
    private javax.swing.JTextField TextFieldNoControl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
