
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrador
 */
public class IngresoGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    String noControl[]={"16041201","16041202","16041203","16041204","16041205","16041206","16041207","16041208","16041209","16041210"};
    String nip[]={"1111","2222","3333","4444","5555","6666","7777","8888","9999","0000"};
    String nombre[]={"CARRILLO MARTINEZ ALEJANDRO DE JESUS","DERAS BONILLA CRISTOPHER JARED","MEDRANO CORRAL ALEJANDRO","SALINAS JAQUEZ BERNARDO","ALARCON GARVALENA LAURA YESENIA","ALVAREZ DELGADO ROQUE EMILIO","AMAYA COLACION HELADIO","CASTAÑEDA ALVARADO CHRISTOPHER","CELIS CARRILLO SAMANTHA DEL CARMEN","CHAVARRIA CABRALES AGUSTIN"};
    Lista_CD p1,f1;
    Lista_FdP p2,f2;
    Lista_TdE p3,f3;
    Lista_MD p4,f4;
    Lista_TdA p5,f5;
    Lista_CI p6,f6;
    Lista_POaO p7,f7;
    Lista_CF p8,f8;
    Lista_Q p9,f9;
    Lista_AL p10,f10;
    Lista_CV p11,f11;
    Lista_EdD p12,f12;
    Lista_CE p13,f13;
    Lista_IdO p14,f14;
    Lista_SO p15,f15;
    public IngresoGUI() {
        initComponents();
        this.setResizable(false);
        //Codigo para poner imagen de fondo
        /*((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/AtM.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());*/
        for(int i=0;i<10;i++){
             if(p1==null){
              Lista_CD q=new Lista_CD();
              q.noControl=noControl[i];
              q.nombre=nombre[i];
              q.liga=null;
              p1=q;
              f1=q;
          }else{
              Lista_CD q=new Lista_CD();
              q.noControl=noControl[i];
              q.nombre=nombre[i];
              q.liga=null;
              f1.liga=q;
              f1=q;
          }
             
              if(p2==null){
              Lista_FdP q=new Lista_FdP();
              q.noControl=noControl[i];
              q.nombre=nombre[i];
              q.liga=null;
              p2=q;
              f2=q;
          }else{
              Lista_FdP q=new Lista_FdP();
              q.noControl=noControl[i];
              q.nombre=nombre[i];
              q.liga=null;
              f2.liga=q;
              f2=q;
          }
              
                if(p3==null){
              Lista_TdE q=new Lista_TdE();
              q.noControl=noControl[i];
              q.nombre=nombre[i];
              q.liga=null;
              p3=q;
              f3=q;
          }else{
              Lista_TdE q=new Lista_TdE();
              q.noControl=noControl[i];
              q.nombre=nombre[i];
              q.liga=null;
              f3.liga=q;
              f3=q;
          }
                
                  if(p4==null){
              Lista_MD q=new Lista_MD();
              q.noControl=noControl[i];
              q.nombre=nombre[i];
              q.liga=null;
              p4=q;
              f4=q;
          }else{
              Lista_MD q=new Lista_MD();
              q.noControl=noControl[i];
              q.nombre=nombre[i];
              q.liga=null;
              f4.liga=q;
              f4=q;
          }
                  
            if(p5==null){
              Lista_TdA q=new Lista_TdA();
              q.noControl=noControl[i];
              q.nombre=nombre[i];
              q.liga=null;
              p5=q;
              f5=q;
          }else{
              Lista_TdA q=new Lista_TdA();
              q.noControl=noControl[i];
              q.nombre=nombre[i];
              q.liga=null;
              f5.liga=q;
              f5=q;
          }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número de Control");

        jLabel2.setText("NIP");

        jButton1.setText("INGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel3.setText("SISTEMA INTEGRAL DE INFORMACIÓN");

        jButton2.setText("¡SOY ADMINISTRADOR!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel2)
                        .addGap(71, 71, 71)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButton2)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String no=jTextField1.getText();
        String nip2=jTextField2.getText();
        if(no.equals("") || nip2.equals("")){
            JOptionPane.showMessageDialog(null,"Asegurate de llenar todos los datos de usuario");
        }else{
            int pos=0;
            int bandera=0;
            for(int i=0;i<10;i++){
                if(noControl[i].equals(no)){
                    pos=i;
                    bandera=1;
                    break;
                }
            }
            if(bandera==1){
                if(nip[pos].equals(nip2)){
                   MateriasGUI n=new MateriasGUI();
                   MateriasGUI.jLabel2.setText(nombre[pos]);
                   n.setVisible(true);
                   this.setVisible(false);
                }else{
                JOptionPane.showMessageDialog(null,"El nip ingresado no es correcto");
                jTextField1.setText("");
                jTextField2.setText(""); 
                }
            }else{
                JOptionPane.showMessageDialog(null,"El numero de control no esta registrado");
                jTextField1.setText("");
                jTextField2.setText("");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String usuario=JOptionPane.showInputDialog(null,"Ingresa el usuario");
        if(usuario.equals("admin")){
            String pass=JOptionPane.showInputDialog("Ingresa el nip");
            if(pass.equals("2371")){
                AdministradorGUI n=new AdministradorGUI();
                n.setVisible(true);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null,"EL nip ingresado no es correcto");
            }
        }else{
            JOptionPane.showMessageDialog(null,"EL usuario no es correcto");
        }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
